### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by zuowanbushiwo** [philgzl/brever#12]
Hi @philgzl 
    I found your project through github's code search function,  I have a problem with data augmentation, specifically with respect to reverb. Can you give some guidance on how to implement the fifth section of this [article ](https://arxiv.org/abs/2205.06931) about data augmentation?
Thanks！

**Comment by philgzl** [comment]
Hi, not sure what you mean. I am not familiar with this paper so I wouldn't know how to implement it without really diving into it. My framework might not even apply to their task.

**Comment by zuowanbushiwo** [comment]
Hi , I'm so sorry I didn't express myself clearly.  I mainly don't understand the following words, if you know, can you guide me，thanks！

>The EIRs are augmented with varying delays up to 0.5 s, the direct path energy is modified with a positively biased gain 
 distribution N(12,5) dB

![image](https://user-images.githubusercontent.com/3354428/223592953-77a1f818-bb46-44d1-ae23-baa5bc14686c.png)

**Comment by philgzl** [comment]
Again I am not the author so I can only guess based on the paper. I would directly ask the authors to be sure.

I guess I would implement the delay by padding zeros at the start of the impulse response, after detecting the peak location. The direct-path can be extracted e.g. like [this](https://github.com/philgzl/brever/blob/a03aff2a2485d9a875c251103723925090f3d891/brever/mixture.py#L140) using a given reflection boundary, and then amplified given the random gain.

**Comment by zuowanbushiwo** [comment]
Thank you very much for your reply and I wish you all the best.
